

#define TITRE "TEST CARTE D925ED4"
#define ATTENTE "ATTENTE DEMARRAGE"
#define CONFORME "TEST CONFORME"
#define NON_CONFORME "TEST NON CONFORME"
#define LIGNE_VIDE ""
#define OK_REQUEST "APPUYER SUR OK"
#define PROGRESS "TEST EN COURS"
#define CAVALIERS ""
#define BOARD_REQUEST "POSITIONNER CARTE"
#define ACQ "ATTENTE ACQUITTEMENT"
#define FIN "FIN DE TEST"
#define EN_PROG "PROGRAMMATION"
#define FIN_PROG "FIN PROGRAMMATION"
#define EN_EFFACEMENT "EFFACEMENT"
#define FIN_EFFACEMENT "FIN EFFACEMENT"


void displayManager(char s1[], char s2[], char s3[], char s4[]);